# -*- coding: utf-8 -*-
"""Luas Bangun Datar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tDxlprF2fCHCHj6sKO6uXdAs4jEUQt2l
"""

#Nama : Dandi Purnomo
#NIM : D0221078
#Mata Kuliah : Pemrograman Berorientasi Objek

#Pemanis
def line():
    print("="*50)
    
def enter():
    print("\n")

#Menu  
def menu():
    while True:
        enter()
        line()
        
        print(" MENGHITUNG LUAS BIDANG DATAR ".center(50,"-"))
        print("1. Luas Persegi")
        print("2. Luas Lingkaran")
        print("3. Luas Segitiga")
        
        line()
        menu = input("Pilih Menu : ").lower()
        if menu == "1" or menu == "persegi":
            persegi()
        elif menu == "2" or menu == "lingkaran":
            lingkaran()
        elif menu == "3" or menu == "segitiga":
            segitiga()
        elif menu == "4" or menu == "keluar":
            enter()
            print(" EXIT ".center(50,"="))
            exit()
            
        else:
            print("Periksa pilihan anda!")
            enter()

#Luas Persegi
def persegi():
    enter()
    line()
    print(" LUAS PERSEGI ".center(50,"-"))
    sisi = int(input("Masukkan Panjang Sisi Persegi: "))
    persegi = sisi*sisi
    print("Luas Persegi : ", persegi, " cm²")
    line()
    menu() 

#Luas Lingkaran
def lingkaran():
    enter()
    line()
    print(" LUAS LINGKARAN ".center(50,"-"))
    jj = int(input("Masukkan Panjang Jari-Jari Lingkaran: "))
    lingkaran = 3.14 * jj ** 2
    print("Luas Lingkaran: ", lingkaran, " cm²")
    line()
    menu()

#Luas Segitiga
def segitiga():
    enter()
    line()
    print(" LUAS SEGITIGA ".center(50,"-"))
    alas = int(input("Masukkan Panjang Alas Segitiga: "))
    tinggi = int(input("Masukkan Tinggi Segitiga: "))
    luas = 1/2 * alas * tinggi
    print("Luas Segitiga: ", luas, " cm²")
    line()
    
    menu()
    
menu()